<<<<<<< HEAD
# URI completa de conexión a MongoDB Atlas
mongodb.uri=mongodb+srv://angela:BatmAn977@clase.xq89gc1.mongodb.net/
# Nombre de la base de datos que quieres usar
=======
# URI completa de conexión a MongoDB Atlas
mongodb.uri=mongodb+srv://angela:BatmAn977@clase.xq89gc1.mongodb.net/
# Nombre de la base de datos que quieres usar
>>>>>>> 0b2e203e636caa13e7fb62219d0b34690426ce80
mongodb.database=hoteles